name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Make hello_test.sh executable
      run: |
        chmod +x ./.tests/hello_test.sh
        chmod +x ./.tests/line2_checker_test.sh
    - name: hello-world-test
      id: hello-world-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: hello-world-test
        setup-command: ''
        command: "./.tests/hello_test.sh"
        input: ''
        expected-output: 'Hello'
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: line2-test
      id: line2-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: line2-test
        setup-command: ''
        command: "./.tests/line2_checker_test.sh"
        input: ''
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-WORLD-TEST_RESULTS: "${{steps.hello-world-test.outputs.result}}"
        LINE2-TEST_RESULTS: "${{steps.line2-test.outputs.result}}"
      with:
        runners: hello-world-test,line2-test
