name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Make hello_test.sh executable
      run: |
        chmod +x ./.tests/hello_test.sh
    - name: ".tests/line2_test.py"
      id: tests-line2_test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: output test
      id: output-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: output test
        setup-command: ''
        command: "./.tests/hello_test.sh"
        input: ''
        expected-output: 'Hello World!'
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-LINE2_TEST-PY_RESULTS: "${{steps.tests-line2_test-py.outputs.result}}"
        OUTPUT-TEST_RESULTS: "${{steps.output-test.outputs.result}}"
      with:
        runners: tests-line2_test-py,output-test
